### ISSUE TITLE
Package.activateConfig is deprecated.

### ISSUE THREAD

**Issue by aceross** [AtomLinter/linter-mcs#4]
Thought I would open this issue for your attention. Output from Atom Editor:

Use a config schema instead. See the configuration section
of https://atom.io/docs/latest/hacking-atom-package-word-count and
https://atom.io/docs/api/latest/Config for more details
```
Package.activateConfig (/opt/atom/resources/app.asar/src/package.js:265:11)
Package.activateNow (/opt/atom/resources/app.asar/src/package.js:236:14)
<unknown> (/opt/atom/resources/app.asar/src/package.js:221:30)
Package.measure (/opt/atom/resources/app.asar/src/package.js:165:15)
Package.activate (/opt/atom/resources/app.asar/src/package.js:213:14)
PackageManager.activatePackage (/opt/atom/resources/app.asar/src/package-manager.js:452:21)
```

**Comment by aceross** [comment]
Saw that OmniSharp is being used instead. Closing issue.

**Comment by ma55acre** [comment]
I have the same error.
Package.activateConfig - \AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:265:11
Package.activateNow - \AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:236:14
<unknown> - \AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:221:30
Package.measure -\Emma\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:165:15
Package.activate - \AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:213:14
PackageManager.activatePackage - AppData\Local\atom\app-1.0.2\resources\app.asar\src\package-manager.js:452:21

  "activationCommands": {
    "atom-workspace": ["foo:bar", "foo:baz"],
    "atom-text-editor": ["foo:quux"]
  }

Report Issue
Package.getActivationCommands - AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:808:9
Package.hasActivationCommands - AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:733:20
<unknown> - AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:187:24
Package.measure - AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:165:15
Package.load - AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:179:12
PackageManager.loadPackage - ppData\Local\atom\app-1.0.2\resources\app.asar\src\package-manager.js:372:14
